image: jelaniwoods/appdev2021-omnicalc-debug@sha256:10d2892e2fc675042838077538d29b9d8903a78312a95601b3ec50ad62349b7f

tasks:
  - command: bundle install
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - wingrunr21.vscode-ruby
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
